version: '3.4'
services:
  viewfile:
    image: goviewfile:v0.7
    restart: always
    volumes:
      - ./main:/var/www/GoViewFile/main
      - ./config/:/var/www/GoViewFile/config/
    entrypoint:
      - /var/www/GoViewFile/main
    ports:
    - 8082:8082